# Generated by Django 2.2.1 on 2019-05-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190526_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['created'], 'verbose_name': 'Equip'},
        ),
    ]
