# Generated by Django 2.2.1 on 2019-05-26 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190526_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['category', 'created'], 'verbose_name': 'Grup'},
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Infantil'), (1, 'Cadet'), (2, 'Absoluta')], verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Infantil'), (1, 'Cadet'), (2, 'Absoluta')], verbose_name='Categoria'),
        ),
    ]
