# Generated by Django 2.2.2 on 2019-06-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190528_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-games_won', 'games_lost', '-points', 'points_against', '-games_played', 'created'], 'verbose_name': 'Equip'},
        ),
    ]
