# Generated by Django 2.2.2 on 2019-06-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0008_auto_20190611_1533'), ('main', '0009_auto_20190611_1534'), ('main', '0010_auto_20190611_1537')]

    dependencies = [
        ('main', '0007_auto_20190610_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_as_away_team', to='main.Team', verbose_name='Equip visitant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_as_home_team', to='main.Team', verbose_name='Equip local'),
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom'),
        ),
    ]
