# Generated by Django 2.2.2 on 2019-06-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190611_1533_squashed_0010_auto_20190611_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='modality',
            field=models.CharField(choices=[('masc', 'Masculí'), ('fem', 'Femení')], max_length=255, verbose_name='Modalitat'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.CharField(choices=[('masc', 'Masculí'), ('fem', 'Femení')], max_length=255, verbose_name='Modalitat'),
        ),
    ]
