# Generated by Django 2.2.2 on 2019-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190612_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='double_round',
            field=models.BooleanField(default=False, verbose_name='Doble volta?'),
        ),
    ]
