# Generated by Django 3.2.13 on 2022-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_group_double_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Correu electrònic de contacte'),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom del responsable de l'equip"),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name="Telèfon del responsable de l'equip"),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Infantil'), (1, 'Cadet'), (3, 'Junior'), (4, 'Senior'), (5, 'Veterans')], verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='group',
            name='modality',
            field=models.CharField(choices=[('masc', 'Masculí'), ('fem', 'Femení'), ('mix', 'Mixte')], max_length=255, verbose_name='Modalitat'),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Infantil'), (1, 'Cadet'), (3, 'Junior'), (4, 'Senior'), (5, 'Veterans')], verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.CharField(choices=[('masc', 'Masculí'), ('fem', 'Femení'), ('mix', 'Mixte')], max_length=255, verbose_name='Modalitat'),
        ),
    ]
