# Generated by Django 4.0.5 on 2022-06-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_group_double_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamForbiddenSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Des de les')),
                ('end_time', models.TimeField(verbose_name='Fins les')),
            ],
            options={
                'verbose_name': 'Franja de temps on no poden jugar',
                'verbose_name_plural': 'Franges de temps on no poden jugar',
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['created'], 'verbose_name': 'Grup'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['my_order'], 'verbose_name': 'Partit'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-competition_points', '-games_won', '-points', 'points_against', 'created'], 'verbose_name': 'Equip'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='category',
        ),
        migrations.RemoveField(
            model_name='group',
            name='double_round',
        ),
        migrations.RemoveField(
            model_name='group',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='match',
            name='game_field',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_time',
        ),
        migrations.AddField(
            model_name='group',
            name='competition_type',
            field=models.CharField(choices=[('single', 'Partit unic'), ('double', 'Anada i tornada')], default='single', max_length=20, verbose_name='Tipus de competicio'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('competition', 'Competició'), ('friendly', 'Amistós'), ('final', 'Final')], default='competition', max_length=255, verbose_name='Tipus'),
        ),
        migrations.AddField(
            model_name='match',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='team',
            name='competition_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Punts'),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Correu electrònic de contacte'),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom del responsable de l'equip"),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name="Telèfon del responsable de l'equip"),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Utilitzar per fer grups manuals. Per defecte sera "Categoria Modalitat"', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True, help_text='Utilitzar per fer partits manuals. Per defecte sera "Equip local vs Equip visitant"', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.PositiveIntegerField(choices=[(10, 'Mini'), (20, 'Infantil'), (30, 'Cadet'), (50, 'Junior'), (60, 'Senior'), (70, 'Veterans')], verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.CharField(choices=[('masc', 'Masculí'), ('fem', 'Femení'), ('mix', 'Mixte')], max_length=255, verbose_name='Modalitat'),
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.AddField(
            model_name='teamforbiddenslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
