# Generated by Django 2.2.28 on 2022-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220616_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='double_round',
        ),
        migrations.AddField(
            model_name='group',
            name='competition_type',
            field=models.CharField(choices=[('single', 'Partit unic'), ('double', 'Anada i tornada')], default='single', max_length=20, verbose_name='Tipus de competicio'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_field',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pista 1'), (2, 'Pista 2')], verbose_name='Pista'),
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
