# Generated by Django 2.2.28 on 2022-06-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220619_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('category', 'modality')},
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
    ]
