# Generated by Django 3.2.25 on 2024-06-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='teams_file',
            field=models.FileField(blank=True, upload_to='teams', verbose_name='CSV amb els equips'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='available_fields',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Pistes disponibles'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='match_length',
            field=models.PositiveSmallIntegerField(default=20, help_text='En minuts', verbose_name="Durada d'un partit"),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='start_datetime',
            field=models.DateTimeField(default='2024-06-21 19:00', verbose_name='Data'),
        ),
    ]
