# Generated by Django 3.2.25 on 2024-06-19 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20240619_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 0), verbose_name='Data'),
        ),
    ]
