# Generated by Django 3.2.13 on 2022-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_groupforbiddenslot_teamforbiddenslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupforbiddenslot',
            options={'verbose_name': 'Franja de temps on no poden jugar', 'verbose_name_plural': 'Franges de temps on no poden jugar'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['order'], 'verbose_name': 'Partit'},
        ),
        migrations.AlterModelOptions(
            name='teamforbiddenslot',
            options={'verbose_name': 'Franja de temps on no poden jugar', 'verbose_name_plural': 'Franges de temps on no poden jugar'},
        ),
        migrations.AddField(
            model_name='match',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupforbiddenslot',
            name='end_time',
            field=models.TimeField(verbose_name='Fins les'),
        ),
        migrations.AlterField(
            model_name='groupforbiddenslot',
            name='start_time',
            field=models.TimeField(verbose_name='Des de les'),
        ),
        migrations.AlterField(
            model_name='teamforbiddenslot',
            name='end_time',
            field=models.TimeField(verbose_name='Fins les'),
        ),
        migrations.AlterField(
            model_name='teamforbiddenslot',
            name='start_time',
            field=models.TimeField(verbose_name='Des de les'),
        ),
    ]
