# Generated by Django 3.2.25 on 2024-06-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_siteconfiguration_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='rules_file',
            field=models.FileField(blank=True, upload_to='rules', verbose_name='Normes generals'),
        ),
    ]
