# Generated by Django 4.0.5 on 2022-06-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220619_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['my_order'], 'verbose_name': 'Partit'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='order',
        ),
        migrations.AddField(
            model_name='match',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
