# Generated by Django 4.0.5 on 2022-06-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_match_options_remove_match_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordre'),
        ),
    ]
